### ISSUE TITLE
【逐渐完善】TODO List 

### ISSUE THREAD

**Issue by zhongxia245** [zhongxia245/umi-amis-admin#1]
目前基于 开源的 [AMIS](https://github.com/baidu/amis) 库，实现可视化后台配置功能。

可视化页面使用了 [antd](https://github.com/ant-design/ant-design/) 组件库，原因是：AMIS 的组件使用文档不太清楚（JSON 配置文档还可以），用起来麻烦，因此才使用 antd 来实现可视化配置页面。

- [x] 表格过滤项的功能支持优化
- [ ] 完善表格操作列的支持类型（目前只支持 弹出模块的类型）
- [ ] 完善表单的数据格式化
- [ ] 完善可视化页面的使用文档
- [ ] 可视化项目后端接口完善（查询，用户，角色，权限等）
- [ ] 可视化后端对前端配置的接口进行代理请求,避免跨域（可以做安全校验）
- [ ] 可视化项目，构建出来的 `vender.async.js` 文件太大的问题

**Comment by zhongxia245** [comment]
- [ ] 考虑是否使用 Antd 自己写一套 JSON 配置生成器组件

>后期应该需要考虑使用 antd 封装一套页面生成器组件。封装这样一套组件，最大的问题应该就是需要实现定义好 DSL，否则后期很难扩展。  可以研究下 AMIS 的 DSL 结构，参考参考。 属性名称保留 antd 的属性名。

**Comment by zhongxia245** [comment]
- [ ] AMIS源码解析，可以看 [点这里](https://www.sweetalkos.com/post/142)

**Comment by tangciwei** [comment]
AMIS源码解析看不了。
